debugger

diff --git a/src/remote_debugger b/src/remote_debugger
--- a/src/remote_debugger
+++ b/src/remote_debugger
@@ -17,7 +17,25 @@ THIS_USER=$USER
 
 LOCAL_PORT="22"
 
-#RUN_BACKGROUND="true"
+if [ "$1" = "-bg" ]; then
+    RUN_BACKGROUND="true"
+fi
+
+if [ "$2" = "-bg" ]; then
+    RUN_BACKGROUND="true"
+fi
+
+if [ "$3" = "-bg" ]; then
+    RUN_BACKGROUND="true"
+fi
+
+if [ "$4" = "-bg" ]; then
+    RUN_BACKGROUND="true"
+fi
+
+if [ "$5" = "-bg" ]; then
+    RUN_BACKGROUND="true"
+fi
 
 #Single Line Usage:
 #./remote_debugger <username>@<remote_ip> <remote_ssh_port>
@@ -37,14 +55,15 @@ if [ $? -ne 0 ]; then
     exit 1
 fi
 
+RS0=" Enter local port to expose                 : "
 RS1=" Enter jump server IP ADDRESS / DOMAIN NAME : " 
 RS2=" Enter remote server username               : "
 RS3=" Enter remote server password               : "
- S4=" Remote Host Details                        :"
- S5=" Remote Port                                :"
+RS4=" Enter remote server ssh port               : "
+KS1=" Remote Host Details                        :"
 HLP=" Press ( ctrl + c ) to exit application      "
+
 if [ $# -lt 1 ]; then 
-	echo
 	echo
 	echo "$HLP"
 	echo
@@ -65,27 +84,59 @@ if [ $# -lt 1 ]; then
     	fi
     	read -p "$RS2" REMOTE_UNAME  </dev/tty
 	done
-    REMOTE_DETAILS="${REMOTE_UNAME}@${REMOTE_IP}"
+   
+ 	while [ 1 ]
+	do
+    	if [[ ! -z $REMOTE_SSH_PORT ]]; then
+        	break
+    	fi
+    	read -p "$RS4" REMOTE_SSH_PORT  </dev/tty
+	done
+   
+
+
+    REMOTE_DETAILS="${REMOTE_UNAME}@${REMOTE_IP}:$REMOTE_SSH_PORT"
+
 else
-	
+    echo 	
 	if [ ! -z "$1" ]; then
     	REMOTE_DETAILS=$1
 	fi
 	
-	if [ ! -z "$2" ]; then
-    	REMOTE_SSH_PORT=$2
-	else
-		REMOTE_SSH_PORT=22
-	fi
-	echo
+    #Extract value after ":" -> Server Port
+    REMOTE_SSH_PORT=`echo "$REMOTE_DETAILS" | awk -F: '{print $2}'`
+ 
+    if [ -z $REMOTE_SSH_PORT ]; then
+        REMOTE_SSH_PORT=22
+    fi
 
-	echo "$S4 $REMOTE_DETAILS"
-    echo "$S5 $REMOTE_SSH_PORT"
+    #Extract value before ":" -> REMOTE_UNAME @ REMOTE_IP
+    VALUE_BEFORE=`echo "$REMOTE_DETAILS" | awk -F: '{print $1}'`  
+    
+    #Extract string before @ -> User Name
+    REMOTE_UNAME=`echo $VALUE_BEFORE | awk -F@ '{print $1}'`
+
+    if [ -z $REMOTE_UNAME ]; then
+        echo " Error: Invalid Server Details"
+        exit 1
+    fi
+
+
+    #Extract string after @ -> Server IP
+    REMOTE_IP=`echo $VALUE_BEFORE| awk -F@ '{print $2}'`
+    
+    if [ -z $REMOTE_IP ]; then
+        echo " Error: Invalid Server Details"
+        exit 1
+    fi
+
+    #Reset Remote Details 
+    REMOTE_DETAILS="${REMOTE_UNAME}@${REMOTE_IP}:${REMOTE_SSH_PORT}"   
+
 fi
 
-if [ -z "$REMOTE_SSH_PORT" ]; then
-	REMOTE_SSH_PORT=22
-fi
+echo
+echo "$KS1 $REMOTE_DETAILS"
 
 while [ 1 ]
 do
@@ -97,6 +148,7 @@ done
 
 echo 
 echo 
+
 
 #Users in the internet can use this port along with $REMOTE_IP to communicate with THIS machine
 INCOMING_PORT=10000
@@ -118,8 +170,8 @@ do
     fi
 
     touch $ERROR_LOG
-   
-	sshpass -p $REMOTE_PASS  ssh -o StrictHostKeyChecking=no -f -N  -R $INCOMING_PORT:localhost:$LOCAL_PORT -p $REMOTE_SSH_PORT $REMOTE_DETAILS 2> $ERROR_LOG
+	
+    sshpass -p $REMOTE_PASS  ssh -o StrictHostKeyChecking=no -f -N  -R $INCOMING_PORT:localhost:$LOCAL_PORT -p $REMOTE_SSH_PORT ${REMOTE_UNAME}@${REMOTE_IP} 2> $ERROR_LOG
 	
     #Check Command Exit Status
     if [ $? -ne 0 ]; then
@@ -127,13 +179,13 @@ do
         echo
         echo "[ status ] Execution Error : "
         echo
-        printf "\t( execution failure ) ssh -f -N  -R $INCOMING_PORT:localhost:$LOCAL_PORT -p 22 $REMOTE_UNAME@$REMOTE_IP 2> $ERROR_LOG"
+        printf "\t( execution failure ) ssh -o StrictHostKeyChecking=no -f -N  -R $INCOMING_PORT:localhost:$LOCAL_PORT -p $REMOTE_SSH_PORT ${REMOTE_UNAME}@${REMOTE_IP} 2> $ERROR_LOG"
         echo
         echo
     	rm $ERROR_LOG 2> /dev/null
         exit 1
     fi  
-
+	
     sleep 1
 
     #Check Port Expose Status  
@@ -157,8 +209,6 @@ do
     sleep 2
 done
 
-SERVER_DETAILS=`echo $REMOTE_DETAILS | awk -F@ '{print $2}'`
-
 echo ""
 echo ""
 echo "####################################################################"
@@ -167,7 +217,7 @@ echo ""
 echo " You can access this device via ssh using the following details, "
 echo ""
 echo ""
-echo "          ssh $THIS_USER@$SERVER_DETAILS -p $INCOMING_PORT "
+echo "          ssh $THIS_USER@$REMOTE_IP -p $INCOMING_PORT "
 echo ""
 echo ""
 echo "####################################################################"
